// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0-UApxkyedekGpD5Ld8__537wZQP1UMg',
    appId: '1:393111413911:web:29fa84d9c74684a7f5b5d2',
    messagingSenderId: '393111413911',
    projectId: 'fitex-e972d',
    authDomain: 'fitex-e972d.firebaseapp.com',
    storageBucket: 'fitex-e972d.appspot.com',
    measurementId: 'G-TCPFBN9V71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp88AOlvr4NAccRrjV88mYJ6OZsQeCXG8',
    appId: '1:393111413911:android:5cda2d41f9eca4fbf5b5d2',
    messagingSenderId: '393111413911',
    projectId: 'fitex-e972d',
    storageBucket: 'fitex-e972d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwlfwIL6RxGDFtYfFCKzE0ukMruVwUdY',
    appId: '1:393111413911:ios:be16a09252990afbf5b5d2',
    messagingSenderId: '393111413911',
    projectId: 'fitex-e972d',
    storageBucket: 'fitex-e972d.appspot.com',
    iosClientId: '393111413911-b9occvl2l4buv3pq1t2t55o1nhklt0eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwlfwIL6RxGDFtYfFCKzE0ukMruVwUdY',
    appId: '1:393111413911:ios:be16a09252990afbf5b5d2',
    messagingSenderId: '393111413911',
    projectId: 'fitex-e972d',
    storageBucket: 'fitex-e972d.appspot.com',
    iosClientId: '393111413911-b9occvl2l4buv3pq1t2t55o1nhklt0eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitEx',
  );
}
